const NOMBRES = {
  // areas
  cardiologia: 'Cardiología',
  clinica_medica: 'Clínica médica',
  ginecologia: 'Ginecología',
  infectologia: 'Infectología',
  medicina_legal: 'Medicina legal',
  obstetricia: 'Obstetricia',
  pediatria: 'Pediatría',
  vacunas: 'Vacunas',
  cirugia: 'Cirugía',
  psiquiatria: 'Psiquiatría',
  salud_publica: 'Salud pública',
  farmacologia: 'Farmacología',
  traumatologia: 'Traumatología',
  neurologia: 'Neurología',
  neumonologia: 'Neumonología',
  gastroenterologia: 'Gastroenterología',
  endocrinologia: 'Endocrinología',
  nefrologia: 'Nefrología',
  hematologia: 'Hematología',
  hematologia_adulto: 'Hematología',
  oncologia: 'Oncología',
  reumatologia: 'Reumatología',
  oftalmologia: 'Oftalmología',
  otorrinolaringologia: 'Otorrinolaringología',
  dermatologia: 'Dermatología',
  urologia: 'Urología',
  medicina_familiar: 'Medicina familiar',
  emergentologia: 'Emergentología',
  // subtemas
  cancer_cuello_uterino: 'Cáncer de cuello uterino',
  cancer_mama: 'Cáncer de mama',
  anticoncepcion: 'Anticoncepción',
  embarazo_normal: 'Embarazo normal',
  embarazo_patologico: 'Embarazo patológico',
  parto_normal: 'Parto normal',
  parto_prematuro_rpm: 'Parto prematuro y RPM',
  puerperio: 'Puerperio',
  infecciones_ginecologicas: 'Infecciones ginecológicas',
  patologia_mamaria: 'Patología mamaria',
  endometriosis: 'Endometriosis',
  miomatosis: 'Miomatosis',
  preeclampsia: 'Preeclampsia',
  control_prenatal: 'Control prenatal',
  desarrollo_psicomotor: 'Desarrollo psicomotor',
  nutricion_infantil: 'Nutrición infantil',
  vacunas_calendario: 'Vacunas — calendario nacional',
  calendario_pediatrico: 'Calendario pediátrico',
  vacunas_adulto: 'Vacunas adulto',
  infecciones_respiratorias: 'Infecciones respiratorias',
  neumonia_pediatrica: 'Neumonía pediátrica',
  diarrea_aguda: 'Diarrea aguda',
  maltrato_infantil: 'Maltrato infantil',
  recien_nacido: 'Recién nacido',
  maduracion_neurologica: 'Maduración neurológica',
  cardiopatias_congenitas: 'Cardiopatías congénitas',
  lactancia: 'Lactancia',
  orl_pediatrica: 'ORL pediátrica',
  ORL_pediatrica: 'ORL pediátrica',
  exantematicas: 'Enfermedades exantemáticas',
  'exantemáticas': 'Enfermedades exantemáticas',
  vih_sida: 'VIH / SIDA',
  hiv_sida: 'VIH / SIDA',
  tuberculosis: 'Tuberculosis',
  hepatitis: 'Hepatitis',
  its: 'Infecciones de transmisión sexual',
  chagas: 'Chagas',
  dengue: 'Dengue',
  meningitis: 'Meningitis',
  insuficiencia_cardiaca: 'Insuficiencia cardíaca',
  hipertension: 'Hipertensión arterial',
  sindrome_coronario: 'Síndrome coronario agudo',
  sindromes_coronarios: 'Síndromes coronarios',
  arritmias: 'Arritmias',
  valvulopatias: 'Valvulopatías',
  diabetes: 'Diabetes',
  hipotiroidismo: 'Hipotiroidismo',
  hipertiroidismo: 'Hipertiroidismo',
  obesidad: 'Obesidad',
  trastornos_ionicos: 'Trastornos iónicos',
  epoc: 'EPOC',
  asma: 'Asma',
  neumonia: 'Neumonía',
  insuficiencia_renal: 'Insuficiencia renal',
  insuficiencia_renal_aguda: 'Insuficiencia renal aguda',
  enfermedad_renal_cronica: 'Enfermedad renal crónica',
  litiasis_renal: 'Litiasis renal',
  anemia: 'Anemia',
  anemia_ferropenica: 'Anemia ferropénica',
  anemia_megaloblastica: 'Anemia megaloblástica',
  leucemia: 'Leucemia',
  linfoma: 'Linfoma',
  apendicitis: 'Apendicitis',
  colecistitis: 'Colecistitis',
  obstruccion_intestinal: 'Obstrucción intestinal',
  hernia: 'Hernia',
  trauma: 'Trauma',
  fracturas: 'Fracturas',
  lumbalgia: 'Lumbalgia',
  depresion: 'Depresión',
  esquizofrenia: 'Esquizofrenia',
  trastorno_bipolar: 'Trastorno bipolar',
  ansiedad: 'Ansiedad',
  salud_mental: 'Salud mental',
  responsabilidad_medica: 'Responsabilidad médica',
  consentimiento_informado: 'Consentimiento informado',
  certificacion_defuncion: 'Certificación de defunción',
  epidemiologia: 'Epidemiología',
  bioestadistica: 'Bioestadística',
  prevencion: 'Prevención',
}

export function formatArea(val) {
  if (!val) return ''
  const key = val.trim()
  return NOMBRES[key] ||
    NOMBRES[key.toLowerCase()] ||
    key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())
}

export function formatSubtema(val) {
  return formatArea(val)
}